name: RetailPulse Sales CI Pipeline

env:
  JAVA_VERSION: '23'          # Centralized JDK version
  DISTRIBUTION: 'temurin'     # Centralized distribution
  MAVEN_CACHE: 'maven'        # Centralized cache type

on:
  workflow_dispatch:

  push:
    branches:
      - develop
      - main

  pull_request:
    branches:
      - develop
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  sale-unit-tests:
    name: Sales Unit Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

    - name: Set up JDK
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: ${{ env.DISTRIBUTION }}
        cache: ${{ env.MAVEN_CACHE }}

    - name: Clean Sales Microservice
      run: mvn clean --file pom.xml

    - name: Build Sales Microservice
      run: mvn --batch-mode -DskipTests package --file pom.xml

    - name: Test Sales Microservice
      run: mvn --batch-mode test --file pom.xml

    - name: Generate Coverage Report
      run: mvn jacoco:report --file pom.xml

    - name: Upload Code Coverage Report as Artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
      with:
        name: code-coverage-report
        path: target/site/jacoco/

  sale-sonarqube-scan:
    name: Sales SonarQube Scan
    needs: sale-unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}
          cache: ${{ env.MAVEN_CACHE }}

      - name: Cache SonarQube packages
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}

          restore-keys: ${{ runner.os }}-m2      
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

  sale-snyk-scan:
    name: IAM Snyk Scan
    needs: sale-unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.DISTRIBUTION }}
          cache: ${{ env.MAVEN_CACHE }}

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=$(readlink -f $(which java) | sed 's:bin/java::')" >> $GITHUB_ENV

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate with Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk to check for vulnerabilities (non-blocking)
        run: snyk test --all-projects --org=retailsecurepulse --severity-threshold=low || true
      
      - name: Monitor project in Snyk dashboard
        run: snyk monitor --all-projects --org=retailsecurepulse
      